sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    security:

        # the default value
        handler: sonata.admin.security.handler.role
        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

        admin_permissions:

            # Defaults:
            - CREATE
            - LIST
            - DELETE
            - UNDELETE
            - EXPORT
            - OPERATOR
            - MASTER
    assets:
        extra_javascripts: ["assets/admin/js/theme.js"]
        extra_stylesheets: ["assets/admin/css/theme.css"]
            


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
